# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Cell')),
            ],
        ),
        migrations.CreateModel(
            name='Objectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_text', models.CharField(max_length=400)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Cell')),
            ],
        ),
    ]
