# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20180626_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='text',
        ),
        migrations.AddField(
            model_name='objective',
            name='objective_text',
            field=models.CharField(default='value def', max_length=400),
        ),
    ]
