# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20180703_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellform',
            name='cell_form_name',
            field=models.CharField(default='placeholder name', max_length=200),
        ),
        migrations.AlterField(
            model_name='objective',
            name='objective_text',
            field=models.CharField(max_length=400),
        ),
    ]
