# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20180703_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_meeting_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Cell')),
            ],
        ),
        migrations.RemoveField(
            model_name='cellform',
            name='cell',
        ),
        migrations.RemoveField(
            model_name='cellform',
            name='member',
        ),
        migrations.RemoveField(
            model_name='member',
            name='cell',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='member',
            name='cells',
            field=models.ManyToManyField(to='meetings.Cell'),
        ),
        migrations.AddField(
            model_name='objective',
            name='cell_output',
            field=models.CharField(default='default cell output text', max_length=400),
        ),
        migrations.AddField(
            model_name='objective',
            name='changed_reason',
            field=models.CharField(default='val', max_length=400),
        ),
        migrations.AddField(
            model_name='objective',
            name='completion_status',
            field=models.CharField(default='val', max_length=400),
        ),
        migrations.AddField(
            model_name='objective',
            name='exp_obj_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='objective',
            name='exp_supply_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='objective',
            name='incompletion_reason',
            field=models.CharField(default='val', max_length=400),
        ),
        migrations.AddField(
            model_name='objective',
            name='owner',
            field=models.CharField(default='val', max_length=400),
        ),
        migrations.AlterField(
            model_name='objective',
            name='objective_text',
            field=models.CharField(default='val', max_length=400),
        ),
        migrations.DeleteModel(
            name='CellForm',
        ),
        migrations.AddField(
            model_name='meeting',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Member'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='objectives',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Objective'),
        ),
    ]
