# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_auto_20180705_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cell',
            options={'ordering': ('cell_name',)},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('member_name',)},
        ),
    ]
