# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_auto_20180709_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('file_location', models.CharField(max_length=500)),
                ('valid_com', models.CharField(max_length=500)),
                ('valid_nocom', models.CharField(max_length=500)),
                ('no_val', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='attendee_list',
            field=models.BooleanField(default=False),
        ),
    ]
