# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_auto_20180724_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='objectives',
        ),
        migrations.AlterField(
            model_name='workreview',
            name='no_val',
            field=models.CharField(default='val', max_length=500),
        ),
        migrations.AlterField(
            model_name='workreview',
            name='title',
            field=models.CharField(default='title def', max_length=500),
        ),
        migrations.AlterField(
            model_name='workreview',
            name='valid_com',
            field=models.CharField(default='val', max_length=500),
        ),
        migrations.AlterField(
            model_name='workreview',
            name='valid_nocom',
            field=models.CharField(default='val', max_length=500),
        ),
    ]
