# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_auto_20180724_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workreview',
            name='no_val',
        ),
        migrations.RemoveField(
            model_name='workreview',
            name='valid_com',
        ),
        migrations.RemoveField(
            model_name='workreview',
            name='valid_nocom',
        ),
        migrations.AddField(
            model_name='workreview',
            name='validation',
            field=models.BooleanField(default='hi', verbose_name='Validation: '),
            preserve_default=False,
        ),
    ]
