# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_auto_20180730_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workreview',
            name='validation',
            field=models.BooleanField(default=True, verbose_name='Validation: '),
        ),
    ]
