# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_remove_workreview_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreview',
            name='validate',
            field=models.BooleanField(default=True, verbose_name='Validation: '),
        ),
    ]
