# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0012_workreview_validate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workreview',
            name='validate',
            field=models.CharField(choices=[('valid_nocom', 'Validated without comment'), ('valid_com', 'Validated with comments'), ('no_val', 'Cannot yet be validated')], max_length=500),
        ),
    ]
