# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0014_workreview_content_val'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workreview',
            name='title',
        ),
    ]
