# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-05 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0017_auto_20180803_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='content_val',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='file_location',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='validate',
        ),
    ]
