# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0018_auto_20180805_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='work_review',
            field=models.ForeignKey(default='hi', on_delete=django.db.models.deletion.CASCADE, to='meetings.WorkReview'),
            preserve_default=False,
        ),
    ]
