# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0019_meeting_work_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='work_review',
        ),
    ]
