# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0021_workreview_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workreview',
            name='meeting',
        ),
    ]
