# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0023_workreview_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='cell',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='member',
        ),
        migrations.RemoveField(
            model_name='workreview',
            name='meeting',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
