# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0026_workreview_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreview',
            name='member',
            field=models.ForeignKey(default='def member', on_delete=django.db.models.deletion.CASCADE, to='meetings.Member'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='attendee_list',
            field=multiselectfield.db.fields.MultiSelectField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workreview',
            name='meeting',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='meetings.Meeting'),
        ),
    ]
