# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0029_workreview_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreview',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.Member'),
        ),
    ]
