# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0030_workreview_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='member1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member1', to='meetings.Member'),
        ),
        migrations.AddField(
            model_name='objective',
            name='member2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member2', to='meetings.Member'),
        ),
    ]
