# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0031_auto_20180807_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='res1',
            field=models.CharField(default='val', max_length=400),
        ),
        migrations.AddField(
            model_name='objective',
            name='res2',
            field=models.CharField(default='val', max_length=400),
        ),
    ]
